apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mock-device-plugin
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: mock-device-plugin
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
        app.kubernetes.io/component: mock-device-plugin
    spec:
      serviceAccountName: mock-device-plugin
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      containers:
      - image: mock-device-plugin:latest
        imagePullPolicy: IfNotPresent
        name: mock-device-plugin
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        command:
          - ./device-plugin
          - -v=5
          - --device-config-file=/device-config.yaml
        volumeMounts:
          - name: dp
            mountPath: /var/lib/kubelet/device-plugins
          - name: sys
            mountPath: /sys
          - name: device-config
            mountPath: /device-config.yaml
            subPath: device-config.yaml
      volumes:
        - name: dp
          hostPath:
            path: /var/lib/kubelet/device-plugins
        - name: sys
          hostPath:
            path: /sys
        - name: device-config
          configMap:
            name: mock-scheduler-device

